const COUNTRIES: Array<{
  country: string;
  capital: string;
  type: string;
  continent?: "Europe" | "Asia" | "Africa" | "Oceania" | "America";
  level?: number;
}> = [
  {
    country: "Abkhazia",
    capital: "Sukhumi",
    type: "countryCapital",
    continent: "Europe",
    level: 4,
  },
  {
    country: "Afghanistan",
    capital: "Kabul",
    type: "countryCapital",
    continent: "Asia",
    level: 2,
  },
  // {
  //   "country": "Akrotiri and Dhekelia",
  //   "capital": "Episkopi Cantonment",
  //   "type": "countryCapital"
  // },
  {
    country: "Albania",
    capital: "Tirana",
    type: "countryCapital",
    continent: "Europe",
    level: 2,
  },
  {
    country: "Algeria",
    capital: "Algiers",
    type: "countryCapital",
    continent: "Africa",
    level: 1,
  },
  {
    country: "American Samoa",
    capital: "Pago Pago",
    type: "countryCapital",
    continent: "America",
    level: 4,
  },
  {
    country: "Andorra",
    capital: "Andorra la Vella",
    type: "countryCapital",
    continent: "Europe",
    level: 1,
  },
  {
    country: "Angola",
    capital: "Luanda",
    type: "countryCapital",
    continent: "Africa",
    level: 3,
  },
  { country: "Anguilla", capital: "The Valley", type: "countryCapital" },
  {
    country: "Antigua and Barbuda",
    capital: "St. John's",
    type: "countryCapital",
  },
  {
    country: "Argentina",
    capital: "Buenos Aires",
    type: "countryCapital",
    continent: "America",
    level: 1,
  },
  {
    country: "Armenia",
    capital: "Yerevan",
    type: "countryCapital",
    continent: "Europe",
    level: 3,
  },
  { country: "Aruba", capital: "Oranjestad", type: "countryCapital" },
  {
    country: "Ascension Island",
    capital: "Georgetown",
    type: "countryCapital",
  },
  {
    country: "Australia",
    capital: "Canberra",
    type: "countryCapital",
    continent: "Oceania",
    level: 1,
  },
  {
    country: "Austria",
    capital: "Vienna",
    type: "countryCapital",
    continent: "Europe",
    level: 1,
  },
  {
    country: "Azerbaijan",
    capital: "Baku",
    type: "countryCapital",
    continent: "Asia",
    level: 3,
  },
  {
    country: "Bahamas",
    capital: "Nassau",
    type: "countryCapital",
    continent: "America",
    level: 4,
  },
  {
    country: "Bahrain",
    capital: "Manama",
    type: "countryCapital",
    continent: "Africa",
    level: 3,
  },
  {
    country: "Bangladesh",
    capital: "Dhaka",
    type: "countryCapital",
    continent: "Asia",
    level: 3,
  },
  {
    country: "Barbados",
    capital: "Bridgetown",
    type: "countryCapital",
    continent: "America",
    level: 4,
  },
  {
    country: "Belarus",
    capital: "Minsk",
    type: "countryCapital",
    continent: "Europe",
    level: 2,
  },
  {
    country: "Belgium",
    capital: "Brussels",
    type: "countryCapital",
    continent: "Europe",
    level: 1,
  },
  {
    country: "Belize",
    capital: "Belmopan",
    type: "countryCapital",
    continent: "America",
    level: 3,
  },
  {
    country: "Benin",
    capital: "Porto-Novo",
    type: "countryCapital",
    continent: "Africa",
    level: 3,
  },
  {
    country: "Bermuda",
    capital: "Hamilton",
    type: "countryCapital",
    continent: "America",
    level: 4,
  },
  {
    country: "Bhutan",
    capital: "Thimphu",
    type: "countryCapital",
    continent: "Asia",
    level: 3,
  },
  {
    country: "Bolivia",
    capital: "Sucre",
    type: "countryCapital",
    continent: "America",
    level: 2,
  },
  // { "country": "Bolivia", "capital": "La Paz", "type": "countryCapital" },
  {
    country: "Bosnia and Herzegovina",
    capital: "Sarajevo",
    type: "countryCapital",
    continent: "Europe",
    level: 1,
  },
  {
    country: "Botswana",
    capital: "Gaborone",
    type: "countryCapital",
    continent: "Africa",
    level: 3,
  },
  {
    country: "Brazil",
    capital: "Brasília",
    type: "countryCapital",
    continent: "America",
    level: 1,
  },
  // {
  //   "country": "British Virgin Islands",
  //   "capital": "Road Town",
  //   "type": "countryCapital"
  // },
  {
    country: "Brunei",
    capital: "Bandar Seri Begawan",
    type: "countryCapital",
    continent: "Asia",
    level: 4,
  },
  {
    country: "Bulgaria",
    capital: "Sofia",
    type: "countryCapital",
    continent: "Europe",
    level: 1,
  },
  {
    country: "Burkina Faso",
    capital: "Ouagadougou",
    type: "countryCapital",
    continent: "Africa",
    level: 3,
  },
  {
    country: "Burundi",
    capital: "Bujumbura",
    type: "countryCapital",
    continent: "Africa",
    level: 4,
  },
  {
    country: "Cambodia",
    capital: "Phnom Penh",
    type: "countryCapital",
    continent: "Asia",
    level: 2,
  },
  {
    country: "Cameroon",
    capital: "Yaoundé",
    type: "countryCapital",
    continent: "Africa",
    level: 3,
  },
  {
    country: "Canada",
    capital: "Ottawa",
    type: "countryCapital",
    continent: "America",
    level: 1,
  },
  { country: "Cape Verde", capital: "Praia", type: "countryCapital" },
  {
    country: "Cayman Islands",
    capital: "George Town",
    type: "countryCapital",
  },
  {
    country: "Central African Republic",
    capital: "Bangui",
    type: "countryCapital",
    continent: "Africa",
    level: 3,
  },
  {
    country: "Chad",
    capital: "N'Djamena",
    type: "countryCapital",
    continent: "Africa",
    level: 3,
  },
  {
    country: "Chile",
    capital: "Santiago",
    type: "countryCapital",
    continent: "America",
    level: 2,
  },
  {
    country: "China",
    capital: "Beijing",
    type: "countryCapital",
    continent: "Asia",
    level: 1,
  },
  // {
  //   country: "Christmas Island",
  //   capital: "Flying Fish Cove",
  //   type: "countryCapital",
  // },
  // {
  //   "country": "Cocos (Keeling) Islands",
  //   "capital": "West Island",
  //   "type": "countryCapital"
  // },
  {
    country: "Colombia",
    capital: "Bogotá",
    type: "countryCapital",
    continent: "America",
    level: 1,
  },
  {
    country: "Comoros",
    capital: "Moroni",
    type: "countryCapital",
    continent: "Africa",
    level: 4,
  },
  {
    country: "Cook Islands",
    capital: "Avarua",
    type: "countryCapital",
    continent: "America",
    level: 4,
  },
  {
    country: "Costa Rica",
    capital: "San José",
    type: "countryCapital",
    continent: "America",
    level: 2,
  },
  {
    country: "Croatia",
    capital: "Zagreb",
    type: "countryCapital",
    continent: "Europe",
    level: 1,
  },
  {
    country: "Cuba",
    capital: "Havana",
    type: "countryCapital",
    continent: "America",
    level: 1,
  },
  // { country: "Curaçao", capital: "Willemstad", type: "countryCapital" , continent: "America", levle: 4},
  {
    country: "Cyprus",
    capital: "Nicosia",
    type: "countryCapital",
    level: 2,
    continent: "Europe",
  },
  {
    country: "Czech Republic",
    capital: "Prague",
    type: "countryCapital",
    level: 1,
    continent: "Europe",
  },
  {
    country: "Côte d'Ivoire",
    capital: "Yamoussoukro",
    type: "countryCapital",
    level: 2,
    continent: "Africa",
  },
  {
    country: "Democratic Republic of the Congo",
    capital: "Kinshasa",
    type: "countryCapital",
    level: 2,
    continent: "Africa",
  },
  {
    country: "Denmark",
    capital: "Copenhagen",
    type: "countryCapital",
    level: 1,
    continent: "Europe",
  },
  {
    country: "Djibouti",
    capital: "Djibouti",
    type: "countryCapital",
    level: 3,
    continent: "Africa",
  },
  {
    country: "Dominica",
    capital: "Roseau",
    type: "countryCapital",
    level: 4,
    continent: "America",
  },
  {
    country: "Dominican Republic",
    capital: "Santo Domingo",
    type: "countryCapital",
    level: 2,
    continent: "America",
  },
  {
    country: "East Timor (Timor-Leste)",
    capital: "Dili",
    type: "countryCapital",
    level: 3,
    continent: "Oceania",
  },
  {
    country: "Easter Island",
    capital: "Hanga Roa",
    type: "countryCapital",
  },
  {
    country: "Ecuador",
    capital: "Quito",
    type: "countryCapital",
    level: 2,
    continent: "America",
  },
  { country: "Egypt", capital: "Cairo", type: "countryCapital" },
  {
    country: "El Salvador",
    capital: "San Salvador",
    type: "countryCapital",
    level: 1,
    continent: "America",
  },
  {
    country: "Equatorial Guinea",
    capital: "Malabo",
    type: "countryCapital",
    level: 3,
    continent: "Africa",
  },
  {
    country: "Eritrea",
    capital: "Asmara",
    type: "countryCapital",
    level: 3,
    continent: "Africa",
  },
  {
    country: "Estonia",
    capital: "Tallinn",
    type: "countryCapital",
    level: 2,
    continent: "Europe",
  },
  {
    country: "Ethiopia",
    capital: "Addis Ababa",
    type: "countryCapital",
    level: 3,
    continent: "Africa",
  },
  // {
  //   "country": "Falkland Islands",
  //   "capital": "Stanley",
  //   "type": "countryCapital"
  // },
  {
    country: "Faroe Islands",
    capital: "Tórshavn",
    type: "countryCapital",
    level: 4,
    continent: "Europe",
  },
  {
    country: "Federated States of Micronesia",
    capital: "Palikir",
    type: "countryCapital",
    level: 4,
    continent: "Oceania",
  },
  {
    country: "Fiji",
    capital: "Suva",
    type: "countryCapital",
    level: 3,
    continent: "Oceania",
  },
  {
    country: "Finland",
    capital: "Helsinki",
    type: "countryCapital",
    level: 1,
    continent: "Europe",
  },
  {
    country: "France",
    capital: "Paris",
    type: "countryCapital",
    level: 1,
    continent: "Europe",
  },
  // {
  //   country: "French Guiana",
  //   capital: "Cayenne",
  //   type: "countryCapital",
  // },
  // {
  //   "country": "French Polynesia",
  //   "capital": "Papeete",
  //   "type": "countryCapital"
  // },
  {
    country: "Gabon",
    capital: "Libreville",
    type: "countryCapital",
    level: 3,
    continent: "Africa",
  },
  {
    country: "Gambia",
    capital: "Banjul",
    type: "countryCapital",
    level: 3,
    continent: "Africa",
  },
  {
    country: "Georgia",
    capital: "Tbilisi",
    type: "countryCapital",
    level: 2,
    continent: "Europe",
  },
  {
    country: "Germany",
    capital: "Berlin",
    type: "countryCapital",
    level: 1,
    continent: "Europe",
  },
  {
    country: "Ghana",
    capital: "Accra",
    type: "countryCapital",
    level: 3,
    continent: "Africa",
  },
  {
    country: "Gibraltar",
    capital: "Gibraltar",
    type: "countryCapital",
    level: 1,
    continent: "Europe",
  },
  {
    country: "Greece",
    capital: "Athens",
    type: "countryCapital",
    level: 1,
    continent: "Europe",
  },
  {
    country: "Greenland",
    capital: "Nuuk",
    type: "countryCapital",
    level: 3,
    continent: "America",
  },
  {
    country: "Grenada",
    capital: "St. George's",
    type: "countryCapital",
    level: 4,
    continent: "America",
  },
  // { "country": "Guam", "capital": "Hagåtña", "type": "countryCapital" },
  {
    country: "Guatemala",
    capital: "Guatemala City",
    type: "countryCapital",
    level: 1,
    continent: "America",
  },
  // {
  //   "country": "Guernsey",
  //   "capital": "St. Peter Port",
  //   "type": "countryCapital"
  // },
  {
    country: "Guinea",
    capital: "Conakry",
    type: "countryCapital",
    level: 3,
    continent: "Africa",
  },
  {
    country: "Guinea-Bissau",
    capital: "Bissau",
    type: "countryCapital",
    level: 1,
    continent: "Africa",
  },
  {
    country: "Guyana",
    capital: "Georgetown",
    type: "countryCapital",
    level: 4,
    continent: "America",
  },
  {
    country: "Haiti",
    capital: "Port-au-Prince",
    type: "countryCapital",
    level: 2,
    continent: "America",
  },
  {
    country: "Honduras",
    capital: "Tegucigalpa",
    type: "countryCapital",
    level: 2,
    continent: "America",
  },
  {
    country: "Hungary",
    capital: "Budapest",
    type: "countryCapital",
    level: 1,
    continent: "Europe",
  },
  {
    country: "Iceland",
    capital: "Reykjavík",
    type: "countryCapital",
    level: 3,
    continent: "Europe",
  },
  {
    country: "India",
    capital: "New Delhi",
    type: "countryCapital",
    level: 1,
    continent: "Asia",
  },
  {
    country: "Indonesia",
    capital: "Jakarta",
    type: "countryCapital",
    level: 1,
    continent: "Asia",
  },
  {
    country: "Iran",
    capital: "Tehran",
    type: "countryCapital",
    level: 1,
    continent: "Asia",
  },
  {
    country: "Iraq",
    capital: "Baghdad",
    type: "countryCapital",
    level: 2,
    continent: "Asia",
  },
  {
    country: "Ireland",
    capital: "Dublin",
    type: "countryCapital",
    level: 1,
    continent: "Europe",
  },
  // { "country": "Isle of Man", "capital": "Douglas", "type": "countryCapital" },
  {
    country: "Israel",
    capital: "Tel-Aviv",
    type: "countryCapital",
    level: 1,
    continent: "Asia",
  },
  {
    country: "Italy",
    capital: "Rome",
    type: "countryCapital",
    level: 1,
    continent: "Europe",
  },
  {
    country: "Jamaica",
    capital: "Kingston",
    type: "countryCapital",
    continent: "America",
  },
  {
    country: "Japan",
    capital: "Tokyo",
    type: "countryCapital",
    continent: "Asia",
  },
  {
    country: "Jersey",
    capital: "St. Helier",
    type: "countryCapital",
    continent: "Europe",
  },
  {
    country: "Jordan",
    capital: "Amman",
    type: "countryCapital",
    continent: "Asia",
  },
  {
    country: "Kazakhstan",
    capital: "Astana",
    type: "countryCapital",
    continent: "Asia",
  },
  {
    country: "Kenya",
    capital: "Nairobi",
    type: "countryCapital",
    continent: "Africa",
  },
  {
    country: "Kiribati",
    capital: "Tarawa",
    type: "countryCapital",
    continent: "Oceania",
  },
  {
    country: "Kosovo",
    capital: "Pristina",
    type: "countryCapital",
    continent: "Europe",
  },
  {
    country: "Kuwait",
    capital: "Kuwait City",
    type: "countryCapital",
    continent: "Asia",
  },
  {
    country: "Kyrgyzstan",
    capital: "Bishkek",
    type: "countryCapital",
    continent: "Asia",
  },
  {
    country: "Laos",
    capital: "Vientiane",
    type: "countryCapital",
    continent: "Asia",
  },
  {
    country: "Latvia",
    capital: "Riga",
    type: "countryCapital",
    continent: "Europe",
  },
  {
    country: "Lebanon",
    capital: "Beirut",
    type: "countryCapital",
    continent: "Asia",
  },
  {
    country: "Lesotho",
    capital: "Maseru",
    type: "countryCapital",
    continent: "Africa",
  },
  {
    country: "Liberia",
    capital: "Monrovia",
    type: "countryCapital",
    continent: "Africa",
  },
  {
    country: "Libya",
    capital: "Tripoli",
    type: "countryCapital",
    continent: "Africa",
  },
  {
    country: "Liechtenstein",
    capital: "Vaduz",
    type: "countryCapital",
    continent: "Europe",
  },
  {
    country: "Lithuania",
    capital: "Vilnius",
    type: "countryCapital",
    continent: "Europe",
  },
  {
    country: "Luxembourg",
    capital: "Luxembourg",
    type: "countryCapital",
    continent: "Europe",
  },
  {
    country: "Macedonia",
    capital: "Skopje",
    type: "countryCapital",
    continent: "Europe",
  },
  {
    country: "Madagascar",
    capital: "Antananarivo",
    type: "countryCapital",
    continent: "Africa",
  },
  {
    country: "Malawi",
    capital: "Lilongwe",
    type: "countryCapital",
    continent: "Africa",
  },
  {
    country: "Malaysia",
    capital: "Kuala Lumpur",
    type: "countryCapital",
    continent: "Asia",
  },
  {
    country: "Maldives",
    capital: "Malé",
    type: "countryCapital",
    continent: "Asia",
  },
  {
    country: "Mali",
    capital: "Bamako",
    type: "countryCapital",
    continent: "Africa",
  },
  {
    country: "Malta",
    capital: "Valletta",
    type: "countryCapital",
    continent: "Europe",
  },
  {
    country: "Mauritania",
    capital: "Nouakchott",
    type: "countryCapital",
    continent: "Africa",
  },
  {
    country: "Mauritius",
    capital: "Port Louis",
    type: "countryCapital",
    continent: "Africa",
  },
  {
    country: "Mexico",
    capital: "Mexico City",
    type: "countryCapital",
    continent: "America",
  },
  {
    country: "Moldova",
    capital: "Chisinau",
    type: "countryCapital",
    continent: "Europe",
  },
  {
    country: "Monaco",
    capital: "Monaco",
    type: "countryCapital",
    continent: "Europe",
  },
  {
    country: "Mongolia",
    capital: "Ulaanbaatar",
    type: "countryCapital",
    continent: "Asia",
  },
  {
    country: "Montenegro",
    capital: "Podgorica",
    type: "countryCapital",
    continent: "Europe",
  },
  {
    country: "Montserrat",
    capital: "Plymouth",
    type: "countryCapital",
    continent: "America",
  },
  {
    country: "Morocco",
    capital: "Rabat",
    type: "countryCapital",
    continent: "Africa",
  },
  {
    country: "Mozambique",
    capital: "Maputo",
    type: "countryCapital",
    continent: "Africa",
  },
  {
    country: "Myanmar",
    capital: "Naypyidaw",
    type: "countryCapital",
    continent: "Asia",
  },
  {
    country: "Namibia",
    capital: "Windhoek",
    type: "countryCapital",
    continent: "Africa",
  },
  {
    country: "Nauru",
    capital: "Yaren",
    type: "countryCapital",
    continent: "Oceania",
  },
  {
    country: "Nepal",
    capital: "Kathmandu",
    type: "countryCapital",
    continent: "Asia",
  },
  {
    country: "Netherlands",
    capital: "Amsterdam",
    type: "countryCapital",
    continent: "Europe",
  },
  {
    country: "New Caledonia",
    capital: "Nouméa",
    type: "countryCapital",
    continent: "Oceania",
  },
  {
    country: "New Zealand",
    capital: "Wellington",
    type: "countryCapital",
    continent: "Oceania",
  },
  {
    country: "Nicaragua",
    capital: "Managua",
    type: "countryCapital",
    continent: "America",
  },
  {
    country: "Niger",
    capital: "Niamey",
    type: "countryCapital",
    continent: "Africa",
  },
  {
    country: "Nigeria",
    capital: "Abuja",
    type: "countryCapital",
    continent: "Africa",
  },
  {
    country: "Niue",
    capital: "Alofi",
    type: "countryCapital",
    continent: "Oceania",
  },
  {
    country: "North Korea",
    capital: "Pyongyang",
    type: "countryCapital",
    continent: "Asia",
  },
  {
    country: "Northern Cyprus",
    capital: "Nicosia",
    type: "countryCapital",
    continent: "Asia",
  },
  {
    country: "United Kingdom Northern Ireland",
    capital: "Belfast",
    type: "countryCapital",
    continent: "Europe",
  },
  {
    country: "Norway",
    capital: "Oslo",
    type: "countryCapital",
    continent: "Europe",
  },
  {
    country: "Oman",
    capital: "Muscat",
    type: "countryCapital",
    continent: "Asia",
  },
  {
    country: "Pakistan",
    capital: "Islamabad",
    type: "countryCapital",
    continent: "Asia",
  },
  {
    country: "Palau",
    capital: "Ngerulmud",
    type: "countryCapital",
    continent: "Oceania",
  },
  {
    country: "Panama",
    capital: "Panama City",
    type: "countryCapital",
    continent: "America",
  },
  {
    country: "Papua New Guinea",
    capital: "Port Moresby",
    type: "countryCapital",
    continent: "Oceania",
  },
  {
    country: "Paraguay",
    capital: "Asunción",
    type: "countryCapital",
    continent: "America",
  },
  {
    country: "Peru",
    capital: "Lima",
    type: "countryCapital",
    continent: "America",
  },
  {
    country: "Philippines",
    capital: "Manila",
    type: "countryCapital",
    continent: "Asia",
  },
  {
    country: "Poland",
    capital: "Warsaw",
    type: "countryCapital",
    continent: "Europe",
  },
  {
    country: "Portugal",
    capital: "Lisbon",
    type: "countryCapital",
    continent: "Europe",
  },
  {
    country: "Puerto Rico",
    capital: "San Juan",
    type: "countryCapital",
    continent: "America",
  },
  {
    country: "Qatar",
    capital: "Doha",
    type: "countryCapital",
    continent: "Asia",
  },
  {
    country: "Republic of China (Taiwan)",
    capital: "Taipei",
    type: "countryCapital",
    continent: "Asia",
  },
  {
    country: "Republic of the Congo",
    capital: "Brazzaville",
    type: "countryCapital",
    continent: "Africa",
  },
  {
    country: "Romania",
    capital: "Bucharest",
    type: "countryCapital",
    continent: "Europe",
  },
  {
    country: "Russia",
    capital: "Moscow",
    type: "countryCapital",
    continent: "Europe",
  },
  {
    country: "Rwanda",
    capital: "Kigali",
    type: "countryCapital",
    continent: "Africa",
  },
  // {
  //   "country": "Saint Barthélemy",
  //   "capital": "Gustavia",
  //   "type": "countryCapital"
  // },
  // {
  //   "country": "Saint Helena",
  //   "capital": "Jamestown",
  //   "type": "countryCapital"
  // },
  {
    country: "Saint Kitts and Nevis",
    capital: "Basseterre",
    type: "countryCapital",
  },
  { country: "Saint Lucia", capital: "Castries", type: "countryCapital" },
  { country: "Saint Martin", capital: "Marigot", type: "countryCapital" },
  // {
  //   "country": "Saint Pierre and Miquelon",
  //   "capital": "St. Pierre",
  //   "type": "countryCapital"
  // },
  {
    country: "Saint Vincent and the Grenadines",
    capital: "Kingstown",
    type: "countryCapital",
  },
  { country: "Samoa", capital: "Apia", type: "countryCapital" },
  {
    country: "San Marino",
    capital: "San Marino",
    type: "countryCapital",
  },
  { country: "Saudi Arabia", capital: "Riyadh", type: "countryCapital" },
  { country: "Scotland", capital: "Edinburgh", type: "countryCapital" },
  { country: "Senegal", capital: "Dakar", type: "countryCapital" },
  { country: "Serbia", capital: "Belgrade", type: "countryCapital" },
  { country: "Seychelles", capital: "Victoria", type: "countryCapital" },
  {
    country: "Sierra Leone",
    capital: "Freetown",
    type: "countryCapital",
  },
  { country: "Singapore", capital: "Singapore", type: "countryCapital" },
  {
    country: "Sint Maarten",
    capital: "Philipsburg",
    type: "countryCapital",
  },
  { country: "Slovakia", capital: "Bratislava", type: "countryCapital" },
  { country: "Slovenia", capital: "Ljubljana", type: "countryCapital" },
  {
    country: "Solomon Islands",
    capital: "Honiara",
    type: "countryCapital",
  },
  { country: "Somalia", capital: "Mogadishu", type: "countryCapital" },
  { country: "Somaliland", capital: "Hargeisa", type: "countryCapital" },
  {
    country: "South Africa",
    capital: "Pretoria",
    type: "countryCapital",
  },
  // {
  //   "country": "South Georgia and the South Sandwich Islands",
  //   "capital": "Grytviken",
  //   "type": "countryCapital"
  // },
  { country: "South Korea", capital: "Seoul", type: "countryCapital" },
  // {
  //   "country": "South Ossetia",
  //   "capital": "Tskhinvali",
  //   "type": "countryCapital"
  // },
  {
    country: "South Sudan",
    capital: "Juba",
    type: "countryCapital",
  },
  { country: "Spain", capital: "Madrid", type: "countryCapital" },
  {
    country: "Sri Lanka",
    capital: "Sri Jayawardenapura Kotte",
    type: "countryCapital",
  },
  { country: "Sudan", capital: "Khartoum", type: "countryCapital" },
  { country: "Suriname", capital: "Paramaribo", type: "countryCapital" },
  { country: "Swaziland", capital: "Mbabane", type: "countryCapital" },
  { country: "Sweden", capital: "Stockholm", type: "countryCapital" },
  { country: "Switzerland", capital: "Bern", type: "countryCapital" },
  { country: "Syria", capital: "Damascus", type: "countryCapital" },
  {
    country: "São Tomé and Príncipe",
    capital: "São Tomé",
    type: "countryCapital",
  },
  { country: "Tajikistan", capital: "Dushanbe", type: "countryCapital" },
  { country: "Tanzania", capital: "Dodoma", type: "countryCapital" },
  { country: "Thailand", capital: "Bangkok", type: "countryCapital" },
  { country: "Togo", capital: "Lomé", type: "countryCapital" },
  { country: "Tonga", capital: "Nukuʻalofa", type: "countryCapital" },
  {
    country: "Transnistria",
    capital: "Tiraspol",
    type: "countryCapital",
  },
  {
    country: "Trinidad and Tobago",
    capital: "Port of Spain",
    type: "countryCapital",
  },
  {
    country: "Tristan da Cunha",
    capital: "Edinburgh of the Seven Seas",
    type: "countryCapital",
  },
  { country: "Tunisia", capital: "Tunis", type: "countryCapital" },
  { country: "Turkey", capital: "Ankara", type: "countryCapital" },
  {
    country: "Turkmenistan",
    capital: "Ashgabat",
    type: "countryCapital",
  },
  // {
  //   "country": "Turks and Caicos Islands",
  //   "capital": "Cockburn Town",
  //   "type": "countryCapital"
  // },
  { country: "Tuvalu", capital: "Funafuti", type: "countryCapital" },
  { country: "Uganda", capital: "Kampala", type: "countryCapital" },
  { country: "Ukraine", capital: "Kiev", type: "countryCapital" },
  {
    country: "United Arab Emirates",
    capital: "Abu Dhabi",
    type: "countryCapital",
  },
  {
    country: "United Kingdom; England",
    capital: "London",
    type: "countryCapital",
  },
  {
    country: "United States",
    capital: "Washington, D.C.",
    type: "countryCapital",
  },
  // {
  //   "country": "United States Virgin Islands",
  //   "capital": "Charlotte Amalie",
  //   "type": "countryCapital"
  // },
  { country: "Uruguay", capital: "Montevideo", type: "countryCapital" },
  { country: "Uzbekistan", capital: "Tashkent", type: "countryCapital" },
  { country: "Vanuatu", capital: "Port Vila", type: "countryCapital" },
  {
    country: "Vatican City",
    capital: "Vatican City",
    type: "countryCapital",
  },
  { country: "Venezuela", capital: "Caracas", type: "countryCapital" },
  { country: "Vietnam", capital: "Hanoi", type: "countryCapital" },
  { country: "Wales", capital: "Cardiff", type: "countryCapital" },
  {
    country: "Wallis and Futuna",
    capital: "Mata-Utu",
    type: "countryCapital",
  },
  {
    country: "Western Sahara",
    capital: "El Aaiún",
    type: "countryCapital",
  },
  { country: "Yemen", capital: "Sanaá", type: "countryCapital" },
  { country: "Zambia", capital: "Lusaka", type: "countryCapital" },
  { country: "Zimbabwe", capital: "Harare", type: "countryCapital" },
];

export default COUNTRIES;
