const COUNTRIES: Array<{
  country: string;
  capital: string;
  type: string;
  continent?: "Europe" | "Asia" | "Africa" | "Oceania" | "America";
  level?: number;
}> = [
  {
    country: "Abkhazia",
    capital: "Sukhumi",
    type: "countryCapital",
    continent: "Europe",
    level: 4,
  },
  {
    country: "Afghanistan",
    capital: "Kabul",
    type: "countryCapital",
    continent: "Asia",
    level: 2,
  },
  // {
  //   "country": "Akrotiri and Dhekelia",
  //   "capital": "Episkopi Cantonment",
  //   "type": "countryCapital"
  // },
  {
    country: "Albania",
    capital: "Tirana",
    type: "countryCapital",
    continent: "Europe",
    level: 2,
  },
  {
    country: "Algeria",
    capital: "Algiers",
    type: "countryCapital",
    continent: "Africa",
    level: 1,
  },
  {
    country: "American Samoa",
    capital: "Pago Pago",
    type: "countryCapital",
    continent: "America",
    level: 4,
  },
  {
    country: "Andorra",
    capital: "Andorra la Vella",
    type: "countryCapital",
    continent: "Europe",
    level: 1,
  },
  {
    country: "Angola",
    capital: "Luanda",
    type: "countryCapital",
    continent: "Africa",
    level: 3,
  },
  { country: "Anguilla", capital: "The Valley", type: "countryCapital" },
  {
    country: "Antigua and Barbuda",
    capital: "St. John's",
    type: "countryCapital",
  },
  {
    country: "Argentina",
    capital: "Buenos Aires",
    type: "countryCapital",
    continent: "America",
    level: 1,
  },
  {
    country: "Armenia",
    capital: "Yerevan",
    type: "countryCapital",
    continent: "Europe",
    level: 3,
  },
  { country: "Aruba", capital: "Oranjestad", type: "countryCapital" },
  {
    country: "Ascension Island",
    capital: "Georgetown",
    type: "countryCapital",
  },
  {
    country: "Australia",
    capital: "Canberra",
    type: "countryCapital",
    continent: "Oceania",
    level: 1,
  },
  {
    country: "Austria",
    capital: "Vienna",
    type: "countryCapital",
    continent: "Europe",
    level: 1,
  },
  {
    country: "Azerbaijan",
    capital: "Baku",
    type: "countryCapital",
    continent: "Asia",
    level: 3,
  },
  {
    country: "Bahamas",
    capital: "Nassau",
    type: "countryCapital",
    continent: "America",
    level: 4,
  },
  {
    country: "Bahrain",
    capital: "Manama",
    type: "countryCapital",
    continent: "Africa",
    level: 3,
  },
  {
    country: "Bangladesh",
    capital: "Dhaka",
    type: "countryCapital",
    continent: "Asia",
    level: 3,
  },
  {
    country: "Barbados",
    capital: "Bridgetown",
    type: "countryCapital",
    continent: "America",
    level: 4,
  },
  {
    country: "Belarus",
    capital: "Minsk",
    type: "countryCapital",
    continent: "Europe",
    level: 2,
  },
  {
    country: "Belgium",
    capital: "Brussels",
    type: "countryCapital",
    continent: "Europe",
    level: 1,
  },
  {
    country: "Belize",
    capital: "Belmopan",
    type: "countryCapital",
    continent: "America",
    level: 3,
  },
  {
    country: "Benin",
    capital: "Porto-Novo",
    type: "countryCapital",
    continent: "Africa",
    level: 3,
  },
  {
    country: "Bermuda",
    capital: "Hamilton",
    type: "countryCapital",
    continent: "America",
    level: 4,
  },
  {
    country: "Bhutan",
    capital: "Thimphu",
    type: "countryCapital",
    continent: "Asia",
    level: 3,
  },
  {
    country: "Bolivia",
    capital: "Sucre",
    type: "countryCapital",
    continent: "America",
    level: 2,
  },
  // { "country": "Bolivia", "capital": "La Paz", "type": "countryCapital" },
  {
    country: "Bosnia and Herzegovina",
    capital: "Sarajevo",
    type: "countryCapital",
    continent: "Europe",
    level: 1,
  },
  {
    country: "Botswana",
    capital: "Gaborone",
    type: "countryCapital",
    continent: "Africa",
    level: 3,
  },
  {
    country: "Brazil",
    capital: "Brasília",
    type: "countryCapital",
    continent: "America",
    level: 1,
  },
  // {
  //   "country": "British Virgin Islands",
  //   "capital": "Road Town",
  //   "type": "countryCapital"
  // },
  {
    country: "Brunei",
    capital: "Bandar Seri Begawan",
    type: "countryCapital",
    continent: "Asia",
    level: 4,
  },
  {
    country: "Bulgaria",
    capital: "Sofia",
    type: "countryCapital",
    continent: "Europe",
    level: 1,
  },
  {
    country: "Burkina Faso",
    capital: "Ouagadougou",
    type: "countryCapital",
    continent: "Africa",
    level: 3,
  },
  {
    country: "Burundi",
    capital: "Bujumbura",
    type: "countryCapital",
    continent: "Africa",
    level: 4,
  },
  {
    country: "Cambodia",
    capital: "Phnom Penh",
    type: "countryCapital",
    continent: "Asia",
    level: 2,
  },
  {
    country: "Cameroon",
    capital: "Yaoundé",
    type: "countryCapital",
    continent: "Africa",
    level: 3,
  },
  {
    country: "Canada",
    capital: "Ottawa",
    type: "countryCapital",
    continent: "America",
    level: 1,
  },
  { country: "Cape Verde", capital: "Praia", type: "countryCapital" },
  {
    country: "Cayman Islands",
    capital: "George Town",
    type: "countryCapital",
  },
  {
    country: "Central African Republic",
    capital: "Bangui",
    type: "countryCapital",
    continent: "Africa",
    level: 3,
  },
  {
    country: "Chad",
    capital: "N'Djamena",
    type: "countryCapital",
    continent: "Africa",
    level: 3,
  },
  {
    country: "Chile",
    capital: "Santiago",
    type: "countryCapital",
    continent: "America",
    level: 2,
  },
  {
    country: "China",
    capital: "Beijing",
    type: "countryCapital",
    continent: "Asia",
    level: 1,
  },
  // {
  //   country: "Christmas Island",
  //   capital: "Flying Fish Cove",
  //   type: "countryCapital",
  // },
  // {
  //   "country": "Cocos (Keeling) Islands",
  //   "capital": "West Island",
  //   "type": "countryCapital"
  // },
  {
    country: "Colombia",
    capital: "Bogotá",
    type: "countryCapital",
    continent: "America",
    level: 1,
  },
  {
    country: "Comoros",
    capital: "Moroni",
    type: "countryCapital",
    continent: "Africa",
    level: 4,
  },
  {
    country: "Cook Islands",
    capital: "Avarua",
    type: "countryCapital",
    continent: "America",
    level: 4,
  },
  {
    country: "Costa Rica",
    capital: "San José",
    type: "countryCapital",
    continent: "America",
    level: 2,
  },
  {
    country: "Croatia",
    capital: "Zagreb",
    type: "countryCapital",
    continent: "Europe",
    level: 1,
  },
  {
    country: "Cuba",
    capital: "Havana",
    type: "countryCapital",
    continent: "America",
    level: 1,
  },
  // { country: "Curaçao", capital: "Willemstad", type: "countryCapital" , continent: "America", levle: 4},
  {
    country: "Cyprus",
    capital: "Nicosia",
    type: "countryCapital",
    level: 2,
    continent: "Europe",
  },
  {
    country: "Czech Republic",
    capital: "Prague",
    type: "countryCapital",
    level: 1,
    continent: "Europe",
  },
  {
    country: "Côte d'Ivoire",
    capital: "Yamoussoukro",
    type: "countryCapital",
    level: 2,
    continent: "Africa",
  },
  {
    country: "Democratic Republic of the Congo",
    capital: "Kinshasa",
    type: "countryCapital",
    level: 2,
    continent: "Africa",
  },
  {
    country: "Denmark",
    capital: "Copenhagen",
    type: "countryCapital",
    level: 1,
    continent: "Europe",
  },
  {
    country: "Djibouti",
    capital: "Djibouti",
    type: "countryCapital",
    level: 3,
    continent: "Africa",
  },
  {
    country: "Dominica",
    capital: "Roseau",
    type: "countryCapital",
    level: 4,
    continent: "America",
  },
  {
    country: "Dominican Republic",
    capital: "Santo Domingo",
    type: "countryCapital",
    level: 2,
    continent: "America",
  },
  {
    country: "East Timor (Timor-Leste)",
    capital: "Dili",
    type: "countryCapital",
    level: 3,
    continent: "Oceania",
  },
  {
    country: "Easter Island",
    capital: "Hanga Roa",
    type: "countryCapital",
  },
  {
    country: "Ecuador",
    capital: "Quito",
    type: "countryCapital",
    level: 2,
    continent: "America",
  },
  { country: "Egypt", capital: "Cairo", type: "countryCapital" },
  {
    country: "El Salvador",
    capital: "San Salvador",
    type: "countryCapital",
    level: 1,
    continent: "America",
  },
  {
    country: "Equatorial Guinea",
    capital: "Malabo",
    type: "countryCapital",
    level: 3,
    continent: "Africa",
  },
  {
    country: "Eritrea",
    capital: "Asmara",
    type: "countryCapital",
    level: 3,
    continent: "Africa",
  },
  {
    country: "Estonia",
    capital: "Tallinn",
    type: "countryCapital",
    level: 2,
    continent: "Europe",
  },
  {
    country: "Ethiopia",
    capital: "Addis Ababa",
    type: "countryCapital",
    level: 3,
    continent: "Africa",
  },
  // {
  //   "country": "Falkland Islands",
  //   "capital": "Stanley",
  //   "type": "countryCapital"
  // },
  {
    country: "Faroe Islands",
    capital: "Tórshavn",
    type: "countryCapital",
    level: 4,
    continent: "Europe",
  },
  {
    country: "Federated States of Micronesia",
    capital: "Palikir",
    type: "countryCapital",
    level: 4,
    continent: "Oceania",
  },
  {
    country: "Fiji",
    capital: "Suva",
    type: "countryCapital",
    level: 3,
    continent: "Oceania",
  },
  {
    country: "Finland",
    capital: "Helsinki",
    type: "countryCapital",
    level: 1,
    continent: "Europe",
  },
  {
    country: "France",
    capital: "Paris",
    type: "countryCapital",
    level: 1,
    continent: "Europe",
  },
  // {
  //   country: "French Guiana",
  //   capital: "Cayenne",
  //   type: "countryCapital",
  // },
  // {
  //   "country": "French Polynesia",
  //   "capital": "Papeete",
  //   "type": "countryCapital"
  // },
  {
    country: "Gabon",
    capital: "Libreville",
    type: "countryCapital",
    level: 3,
    continent: "Africa",
  },
  {
    country: "Gambia",
    capital: "Banjul",
    type: "countryCapital",
    level: 3,
    continent: "Africa",
  },
  {
    country: "Georgia",
    capital: "Tbilisi",
    type: "countryCapital",
    level: 2,
    continent: "Europe",
  },
  {
    country: "Germany",
    capital: "Berlin",
    type: "countryCapital",
    level: 1,
    continent: "Europe",
  },
  {
    country: "Ghana",
    capital: "Accra",
    type: "countryCapital",
    level: 3,
    continent: "Africa",
  },
  {
    country: "Gibraltar",
    capital: "Gibraltar",
    type: "countryCapital",
    level: 1,
    continent: "Europe",
  },
  {
    country: "Greece",
    capital: "Athens",
    type: "countryCapital",
    level: 1,
    continent: "Europe",
  },
  {
    country: "Greenland",
    capital: "Nuuk",
    type: "countryCapital",
    level: 3,
    continent: "America",
  },
  {
    country: "Grenada",
    capital: "St. George's",
    type: "countryCapital",
    level: 4,
    continent: "America",
  },
  // { "country": "Guam", "capital": "Hagåtña", "type": "countryCapital" },
  {
    country: "Guatemala",
    capital: "Guatemala City",
    type: "countryCapital",
    level: 1,
    continent: "America",
  },
  // {
  //   "country": "Guernsey",
  //   "capital": "St. Peter Port",
  //   "type": "countryCapital"
  // },
  {
    country: "Guinea",
    capital: "Conakry",
    type: "countryCapital",
    level: 3,
    continent: "Africa",
  },
  {
    country: "Guinea-Bissau",
    capital: "Bissau",
    type: "countryCapital",
    level: 1,
    continent: "Africa",
  },
  {
    country: "Guyana",
    capital: "Georgetown",
    type: "countryCapital",
    level: 4,
    continent: "America",
  },
  {
    country: "Haiti",
    capital: "Port-au-Prince",
    type: "countryCapital",
    level: 2,
    continent: "America",
  },
  {
    country: "Honduras",
    capital: "Tegucigalpa",
    type: "countryCapital",
    level: 2,
    continent: "America",
  },
  {
    country: "Hungary",
    capital: "Budapest",
    type: "countryCapital",
    level: 1,
    continent: "Europe",
  },
  {
    country: "Iceland",
    capital: "Reykjavík",
    type: "countryCapital",
    level: 3,
    continent: "Europe",
  },
  {
    country: "India",
    capital: "New Delhi",
    type: "countryCapital",
    level: 1,
    continent: "Asia",
  },
  {
    country: "Indonesia",
    capital: "Jakarta",
    type: "countryCapital",
    level: 1,
    continent: "Asia",
  },
  {
    country: "Iran",
    capital: "Tehran",
    type: "countryCapital",
    level: 1,
    continent: "Asia",
  },
  {
    country: "Iraq",
    capital: "Baghdad",
    type: "countryCapital",
    level: 2,
    continent: "Asia",
  },
  {
    country: "Ireland",
    capital: "Dublin",
    type: "countryCapital",
    level: 1,
    continent: "Europe",
  },
  // { "country": "Isle of Man", "capital": "Douglas", "type": "countryCapital" },
  {
    country: "Israel",
    capital: "Tel-Aviv",
    type: "countryCapital",
    level: 1,
    continent: "Asia",
  },
  {
    country: "Italy",
    capital: "Rome",
    type: "countryCapital",
    level: 1,
    continent: "Europe",
  },
  { country: "Jamaica", capital: "Kingston", type: "countryCapital" },
  { country: "Japan", capital: "Tokyo", type: "countryCapital" },
  { country: "Jersey", capital: "St. Helier", type: "countryCapital" },
  { country: "Jordan", capital: "Amman", type: "countryCapital" },
  { country: "Kazakhstan", capital: "Astana", type: "countryCapital" },
  { country: "Kenya", capital: "Nairobi", type: "countryCapital" },
  { country: "Kiribati", capital: "Tarawa", type: "countryCapital" },
  { country: "Kosovo", capital: "Pristina", type: "countryCapital" },
  { country: "Kuwait", capital: "Kuwait City", type: "countryCapital" },
  { country: "Kyrgyzstan", capital: "Bishkek", type: "countryCapital" },
  { country: "Laos", capital: "Vientiane", type: "countryCapital" },
  { country: "Latvia", capital: "Riga", type: "countryCapital" },
  { country: "Lebanon", capital: "Beirut", type: "countryCapital" },
  { country: "Lesotho", capital: "Maseru", type: "countryCapital" },
  { country: "Liberia", capital: "Monrovia", type: "countryCapital" },
  { country: "Libya", capital: "Tripoli", type: "countryCapital" },
  { country: "Liechtenstein", capital: "Vaduz", type: "countryCapital" },
  { country: "Lithuania", capital: "Vilnius", type: "countryCapital" },
  {
    country: "Luxembourg",
    capital: "Luxembourg",
    type: "countryCapital",
  },
  { country: "Macedonia", capital: "Skopje", type: "countryCapital" },
  {
    country: "Madagascar",
    capital: "Antananarivo",
    type: "countryCapital",
  },
  { country: "Malawi", capital: "Lilongwe", type: "countryCapital" },
  {
    country: "Malaysia",
    capital: "Kuala Lumpur",
    type: "countryCapital",
  },
  { country: "Maldives", capital: "Malé", type: "countryCapital" },
  { country: "Mali", capital: "Bamako", type: "countryCapital" },
  { country: "Malta", capital: "Valletta", type: "countryCapital" },
  // {
  //   "country": "Marshall Islands",
  //   "capital": "Majuro",
  //   "type": "countryCapital"
  // },
  {
    country: "Mauritania",
    capital: "Nouakchott",
    type: "countryCapital",
  },
  { country: "Mauritius", capital: "Port Louis", type: "countryCapital" },
  { country: "Mexico", capital: "Mexico City", type: "countryCapital" },
  { country: "Moldova", capital: "Chisinau", type: "countryCapital" },
  { country: "Monaco", capital: "Monaco", type: "countryCapital" },
  { country: "Mongolia", capital: "Ulaanbaatar", type: "countryCapital" },
  { country: "Montenegro", capital: "Podgorica", type: "countryCapital" },
  { country: "Montserrat", capital: "Plymouth", type: "countryCapital" },
  { country: "Morocco", capital: "Rabat", type: "countryCapital" },
  { country: "Mozambique", capital: "Maputo", type: "countryCapital" },
  { country: "Myanmar", capital: "Naypyidaw", type: "countryCapital" },
  // {
  //   "country": "Nagorno-Karabakh Republic",
  //   "capital": "Stepanakert",
  //   "type": "countryCapital"
  // },
  { country: "Namibia", capital: "Windhoek", type: "countryCapital" },
  { country: "Nauru", capital: "Yaren", type: "countryCapital" },
  { country: "Nepal", capital: "Kathmandu", type: "countryCapital" },
  {
    country: "Netherlands",
    capital: "Amsterdam",
    type: "countryCapital",
  },
  { country: "New Caledonia", capital: "Nouméa", type: "countryCapital" },
  {
    country: "New Zealand",
    capital: "Wellington",
    type: "countryCapital",
  },
  { country: "Nicaragua", capital: "Managua", type: "countryCapital" },
  { country: "Niger", capital: "Niamey", type: "countryCapital" },
  { country: "Nigeria", capital: "Abuja", type: "countryCapital" },
  { country: "Niue", capital: "Alofi", type: "countryCapital" },
  // {
  //   "country": "Norfolk Island",
  //   "capital": "Kingston",
  //   "type": "countryCapital"
  // },
  {
    country: "North Korea",
    capital: "Pyongyang",
    type: "countryCapital",
  },
  {
    country: "Northern Cyprus",
    capital: "Nicosia",
    type: "countryCapital",
  },
  {
    country: "United Kingdom Northern Ireland",
    capital: "Belfast",
    type: "countryCapital",
  },
  // {
  //   "country": "Northern Mariana Islands",
  //   "capital": "Saipan",
  //   "type": "countryCapital"
  // },
  { country: "Norway", capital: "Oslo", type: "countryCapital" },
  { country: "Oman", capital: "Muscat", type: "countryCapital" },
  { country: "Pakistan", capital: "Islamabad", type: "countryCapital" },
  { country: "Palau", capital: "Ngerulmud", type: "countryCapital" },
  { country: "Panama", capital: "Panama City", type: "countryCapital" },
  {
    country: "Papua New Guinea",
    capital: "Port Moresby",
    type: "countryCapital",
  },
  { country: "Paraguay", capital: "Asunción", type: "countryCapital" },
  { country: "Peru", capital: "Lima", type: "countryCapital" },
  { country: "Philippines", capital: "Manila", type: "countryCapital" },
  // {
  //   "country": "Pitcairn Islands",
  //   "capital": "Adamstown",
  //   "type": "countryCapital"
  // },
  { country: "Poland", capital: "Warsaw", type: "countryCapital" },
  { country: "Portugal", capital: "Lisbon", type: "countryCapital" },
  { country: "Puerto Rico", capital: "San Juan", type: "countryCapital" },
  { country: "Qatar", capital: "Doha", type: "countryCapital" },
  {
    country: "Republic of China (Taiwan)",
    capital: "Taipei",
    type: "countryCapital",
  },
  {
    country: "Republic of the Congo",
    capital: "Brazzaville",
    type: "countryCapital",
  },
  { country: "Romania", capital: "Bucharest", type: "countryCapital" },
  { country: "Russia", capital: "Moscow", type: "countryCapital" },
  { country: "Rwanda", capital: "Kigali", type: "countryCapital" },
  // {
  //   "country": "Saint Barthélemy",
  //   "capital": "Gustavia",
  //   "type": "countryCapital"
  // },
  // {
  //   "country": "Saint Helena",
  //   "capital": "Jamestown",
  //   "type": "countryCapital"
  // },
  {
    country: "Saint Kitts and Nevis",
    capital: "Basseterre",
    type: "countryCapital",
  },
  { country: "Saint Lucia", capital: "Castries", type: "countryCapital" },
  { country: "Saint Martin", capital: "Marigot", type: "countryCapital" },
  // {
  //   "country": "Saint Pierre and Miquelon",
  //   "capital": "St. Pierre",
  //   "type": "countryCapital"
  // },
  {
    country: "Saint Vincent and the Grenadines",
    capital: "Kingstown",
    type: "countryCapital",
  },
  { country: "Samoa", capital: "Apia", type: "countryCapital" },
  {
    country: "San Marino",
    capital: "San Marino",
    type: "countryCapital",
  },
  { country: "Saudi Arabia", capital: "Riyadh", type: "countryCapital" },
  { country: "Scotland", capital: "Edinburgh", type: "countryCapital" },
  { country: "Senegal", capital: "Dakar", type: "countryCapital" },
  { country: "Serbia", capital: "Belgrade", type: "countryCapital" },
  { country: "Seychelles", capital: "Victoria", type: "countryCapital" },
  {
    country: "Sierra Leone",
    capital: "Freetown",
    type: "countryCapital",
  },
  { country: "Singapore", capital: "Singapore", type: "countryCapital" },
  {
    country: "Sint Maarten",
    capital: "Philipsburg",
    type: "countryCapital",
  },
  { country: "Slovakia", capital: "Bratislava", type: "countryCapital" },
  { country: "Slovenia", capital: "Ljubljana", type: "countryCapital" },
  {
    country: "Solomon Islands",
    capital: "Honiara",
    type: "countryCapital",
  },
  { country: "Somalia", capital: "Mogadishu", type: "countryCapital" },
  { country: "Somaliland", capital: "Hargeisa", type: "countryCapital" },
  {
    country: "South Africa",
    capital: "Pretoria",
    type: "countryCapital",
  },
  // {
  //   "country": "South Georgia and the South Sandwich Islands",
  //   "capital": "Grytviken",
  //   "type": "countryCapital"
  // },
  { country: "South Korea", capital: "Seoul", type: "countryCapital" },
  // {
  //   "country": "South Ossetia",
  //   "capital": "Tskhinvali",
  //   "type": "countryCapital"
  // },
  {
    country: "South Sudan",
    capital: "Juba",
    type: "countryCapital",
  },
  { country: "Spain", capital: "Madrid", type: "countryCapital" },
  {
    country: "Sri Lanka",
    capital: "Sri Jayawardenapura Kotte",
    type: "countryCapital",
  },
  { country: "Sudan", capital: "Khartoum", type: "countryCapital" },
  { country: "Suriname", capital: "Paramaribo", type: "countryCapital" },
  { country: "Swaziland", capital: "Mbabane", type: "countryCapital" },
  { country: "Sweden", capital: "Stockholm", type: "countryCapital" },
  { country: "Switzerland", capital: "Bern", type: "countryCapital" },
  { country: "Syria", capital: "Damascus", type: "countryCapital" },
  {
    country: "São Tomé and Príncipe",
    capital: "São Tomé",
    type: "countryCapital",
  },
  { country: "Tajikistan", capital: "Dushanbe", type: "countryCapital" },
  { country: "Tanzania", capital: "Dodoma", type: "countryCapital" },
  { country: "Thailand", capital: "Bangkok", type: "countryCapital" },
  { country: "Togo", capital: "Lomé", type: "countryCapital" },
  { country: "Tonga", capital: "Nukuʻalofa", type: "countryCapital" },
  {
    country: "Transnistria",
    capital: "Tiraspol",
    type: "countryCapital",
  },
  {
    country: "Trinidad and Tobago",
    capital: "Port of Spain",
    type: "countryCapital",
  },
  {
    country: "Tristan da Cunha",
    capital: "Edinburgh of the Seven Seas",
    type: "countryCapital",
  },
  { country: "Tunisia", capital: "Tunis", type: "countryCapital" },
  { country: "Turkey", capital: "Ankara", type: "countryCapital" },
  {
    country: "Turkmenistan",
    capital: "Ashgabat",
    type: "countryCapital",
  },
  // {
  //   "country": "Turks and Caicos Islands",
  //   "capital": "Cockburn Town",
  //   "type": "countryCapital"
  // },
  { country: "Tuvalu", capital: "Funafuti", type: "countryCapital" },
  { country: "Uganda", capital: "Kampala", type: "countryCapital" },
  { country: "Ukraine", capital: "Kiev", type: "countryCapital" },
  {
    country: "United Arab Emirates",
    capital: "Abu Dhabi",
    type: "countryCapital",
  },
  {
    country: "United Kingdom; England",
    capital: "London",
    type: "countryCapital",
  },
  {
    country: "United States",
    capital: "Washington, D.C.",
    type: "countryCapital",
  },
  // {
  //   "country": "United States Virgin Islands",
  //   "capital": "Charlotte Amalie",
  //   "type": "countryCapital"
  // },
  { country: "Uruguay", capital: "Montevideo", type: "countryCapital" },
  { country: "Uzbekistan", capital: "Tashkent", type: "countryCapital" },
  { country: "Vanuatu", capital: "Port Vila", type: "countryCapital" },
  {
    country: "Vatican City",
    capital: "Vatican City",
    type: "countryCapital",
  },
  { country: "Venezuela", capital: "Caracas", type: "countryCapital" },
  { country: "Vietnam", capital: "Hanoi", type: "countryCapital" },
  { country: "Wales", capital: "Cardiff", type: "countryCapital" },
  {
    country: "Wallis and Futuna",
    capital: "Mata-Utu",
    type: "countryCapital",
  },
  {
    country: "Western Sahara",
    capital: "El Aaiún",
    type: "countryCapital",
  },
  { country: "Yemen", capital: "Sanaá", type: "countryCapital" },
  { country: "Zambia", capital: "Lusaka", type: "countryCapital" },
  { country: "Zimbabwe", capital: "Harare", type: "countryCapital" },
];

export default COUNTRIES;
